config/routes.rb
Rails.application.routes.draw do
    root "pages#home"
    get "about" => "pages#about" #Created about page
    get "team" => "pages#team" #Created about page
    get "fatima" => "pages#fatima" #Created page for cousin Fatima during visit

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

   def about
   end

   def team
   end

   def fatima
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar inverse navbar-static-top navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://www.google.com">Pinteresting</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
   
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right"> 
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Page", about_path %></li>
        <li><%= link_to "Team", team_path %></li>
        <li><%= link_to "Fatima", fatima_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
		
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
		</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>We are working on our 1-month rails pinteresting app!</p>

app/views/pages/fatima.html.erb
<h1>Fatima pages</h1>
<p>In this home We recycle in this house</p>

app/views/pages/home.html.erb
<div class = "jumbotron">
	<h1>Welcome to my app, Fana</h1>
	<p>Click here to <%= link_to "Sign up", "#", class: "btn-primary btn-lg" %></p>
</div>

app/views/pages/team.html.erb
<h1>Team</h1>
	<p>This is my Team page.</p>
	<p> right now I am a 1-man shop</p>

	<p> BUT</p>
	<p>
	<p> I believe</p>